### ISSUE TITLE
Building the UI

### ISSUE THREAD

**Issue by 0xOrange** [chefgonpachi/MISO#1]
yo.

This is a really interesting project, one that I'm particularly excited for Sushiswap.
I would love to help building out the UI for this(or anything else if needed).

Few questions:
1) Can you explain more about how the fees work? From what I read:
- Fees generated will be a small percentage of the token listing fees 
- 70% will go directly to the token holders 
- 20% as UI incentive for launchpads to use MISO / integrate with other projects
- 10% dev fee
Has anything changed?
2) This is just a suggestion -- It would be cool to also have something like the MoonBase rover, projects can choose to deposit a portion of their tokens which is vested linearly for 1 year. The released tokens are swapped to sushi and distributed proportionately to the Sushi holders. This way the Sushi community is really incentivised to push the projects to succeed.

**Comment by chefgonpachi** [comment]
The MoonBaseRover is a fantastic suggestion, one that might wait until v1 is launched, but would fit perfectly with our ecosystem. Fees were just a suggestion I made in the proposal, will focus on launching first and getting some guidance from the Sushi Core team later.
